[build]
  publish = "frontend"

[[headers]]
  for = "/*.MOV"
  [headers.values]
    Content-Type = "video/quicktime"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mov"
  [headers.values]
    Content-Type = "video/quicktime"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"
